hackison1/Hacktoberfest-2021

Python/great3var2.py
=> greatest number among three with just 2 variable

Python/test1.py
This pull request is the test pull request for Hacktoberfest-2021.
=> Initial Commit for Hacktoberfest

Python/linear_search.py
Added   Linear Search Algorithm
=> Linear Search added

C/hello_world.c
Added C language folder for C programs
=> Added C language Folder

Python/findGay.py
=> Create  findGay.py

Python/addTwoNumbers.py
I have just added a function which return addition of two numbers and also printed the result on output screen
=> simple way to add two number

C/linear search.c
sample output
enter the number of values to be inserted8
enter the value8
enter the value6
enter the value9
enter the value2
enter the value9
enter the value4
enter the value0
enter the value2
enter the element to be searched0
yes
=> created linear search program using C language

concatination_of_array.c
program to concatenate two arrays #hacktoberfest2021
=>  To concatenate two arrays 

Python/number_to_number_name.py
program to  change a Number to number name #3
=> Number_to_number_name.py

Java/IsPalindrome.java
check entered number set is palindrome
=> IsPalindrome

Java/ADTFraction.java
will output arithmetic operations of fractions
=> output arithmetic operations of fractions

Java/LCMFinder.java
This is to find the LCM using java.
=> java LCM finder added

Python/calculator.py, Python/rockpaperscissors.py
The first program is a small yet very interesting time-pass game: Rock, Paper, and Scissors.
And, the second program is a basic calculator with some better features.
=> Added 2 new interesting programs in python

Java/factorial.java
=> factorial program 

C/FibonacciGenerator.c, C/arrayRotation.c, C/binaryToOctal.c
=> Added array rotation program in C

Java/WordCounterApp.java
Check how many words contain in a sentence in java
=> Word count in java

C/new.c
Adding two numbers using call by reference
=> add using call by reference

C/calculateLength.c
=> Calculates length of string

C/date.c
Given number of days, converts into xx Years xx Weeks and xx Days
=> Convert days into year, weeks, days

C/NextGreatestElement.c
Add my contribution for Hacktoberfest 2021
=> Added C program for Next Greatest Element

Python/longest valid substring.py
finds the longest valid substring in a string
=> Create longest valid substring.py

Java/stack-delete-middle-element.java
Java program to delete middle element from the stack.
=> Added one stack problem in Java

C/linear_search
=> added C linear Search

CPP/bfs.cpp
=> Added bfs.cpp

Python/Josephus.py
This is the implementation of Josephus's problem in the python language. Please accept this for the Hacktoberfest 2021 :)
=> Josephus problem in python

Python/knapsack.py, Python/unboundedKnapsack.py
This is the implementation of the Unbounded knapsack problem in the python language. Please accept this for the Hacktoberfest 2021 :)
=> Unbounded knapsack

Python/knapsack.py
This is the implementation of 0/1 Knapsack problem in the python language. Please accept this for the Hacktoberfest 2021 :)
=> 0/1 Knapsack problem in Python

Python/HeapSort.py
This file contains code with proper explanation for performing heap sort in python language. Please accept this pull request for Hacktoberfest 2021 :)
=> Added python program for heap sort

Python/SieveOfEratosthenes.py
Sieve of Eratosthenes is the fastest way to get all the prime number between a given range
**Sample Output :** 
> Range 0-30 in the program
`2 
3 
5 
7 
11
13
17
19
23
29
`
**Time Complexity : Big O (n*log(log(n)))**
[More information about SieveofEratosthenes ](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)
Hope you will merge my PR , Happy Coding :)
=> SieveOfEratosthenes.py (Best Algorithm to find Prime Number Between Given Range)

CPP/SieveOfEratothenes.cpp
SeiveOfEratothenes.cpp algorithms version in C++ 
Happy Coding :)
**Hope you will merge this PR ,Version of Sieve of Eratosthenes for C++**
=> Added a c++ version for SeiveOfEratothenes.cpp
